/* Generated By:JavaCC: Do not edit this line. ExpressionTreeConstants.java Version 5.0 */
package n3phele.service.nShell;

public interface ExpressionTreeConstants
{
  public int JJTFUNCTIONEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTCONDITIONALEXPRESSION = 2;
  public int JJTLOGICALOREXPRESSION = 3;
  public int JJTLOGICALANDEXPRESSION = 4;
  public int JJTEQUALITYEXPRESSION = 5;
  public int JJTRELATIONALEXPRESSION = 6;
  public int JJTADDITIVEEXPRESSION = 7;
  public int JJTMULTIPLICATIVEEXPRESSION = 8;
  public int JJTUNARYEXPRESSION = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTSUBLIST = 11;
  public int JJTLIST = 12;
  public int JJTCONSTANT = 13;


  public String[] jjtNodeName = {
    "functionExpression",
    "void",
    "conditionalExpression",
    "logicalORExpression",
    "logicalANDExpression",
    "equalityExpression",
    "relationalExpression",
    "additiveExpression",
    "multiplicativeExpression",
    "unaryExpression",
    "identifier",
    "subList",
    "list",
    "constant",
  };
}
/* JavaCC - OriginalChecksum=78e45422c6249f4672066ea7e7c360bf (do not edit this line) */
