/* Generated By:JavaCC: Do not edit this line. ExpressionTreeConstants.java Version 5.0 */
package n3phele.service.nShell;

public interface ExpressionTreeConstants
{
  public int JJTFUNCTIONEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTCONDITIONALEXPRESSION = 2;
  public int JJTLOGICALOREXPRESSION = 3;
  public int JJTLOGICALANDEXPRESSION = 4;
  public int JJTEQUALITYEXPRESSION = 5;
  public int JJTRELATIONALEXPRESSION = 6;
  public int JJTADDITIVEEXPRESSION = 7;
  public int JJTMULTIPLICATIVEEXPRESSION = 8;
  public int JJTUNARYEXPRESSION = 9;
  public int JJTUNARYOPERATOR = 10;
  public int JJTLISTINDEXEXPRESSION = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTPRIMARYLISTEXPRESSION = 13;
  public int JJTSUBLIST = 14;
  public int JJTLIST = 15;
  public int JJTCONSTANT = 16;


  public String[] jjtNodeName = {
    "functionExpression",
    "void",
    "conditionalExpression",
    "logicalORExpression",
    "logicalANDExpression",
    "equalityExpression",
    "relationalExpression",
    "additiveExpression",
    "multiplicativeExpression",
    "unaryExpression",
    "unaryOperator",
    "listIndexExpression",
    "identifier",
    "primaryListExpression",
    "subList",
    "list",
    "constant",
  };
}
/* JavaCC - OriginalChecksum=d01856e7d91c3923da3a4efc767fd082 (do not edit this line) */
