/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionConstants.java */
package n3phele.service.nShell;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int REGEX = 6;
  /** RegularExpression Id. */
  int MAX = 7;
  /** RegularExpression Id. */
  int MIN = 8;
  /** RegularExpression Id. */
  int LENGTH = 9;
  /** RegularExpression Id. */
  int ESCAPE = 10;
  /** RegularExpression Id. */
  int UNESCAPE = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 15;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 16;
  /** RegularExpression Id. */
  int HEX_LITERAL = 17;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 18;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int EXPONENT = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int VARSTART = 23;
  /** RegularExpression Id. */
  int VARREST = 24;
  /** RegularExpression Id. */
  int WHITESPACE = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"$$regex(\"",
    "\"$$max(\"",
    "\"$$min(\"",
    "\"$$length(\"",
    "\"$$escape(\"",
    "\"$$unescape(\"",
    "\"$$string(\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<VARSTART>",
    "<VARREST>",
    "<WHITESPACE>",
    "\",\"",
    "\")\"",
    "\"?\"",
    "\":\"",
    "\"|\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
  };

}
