/* Generated By:JavaCC: Do not edit this line. ShellTreeConstants.java Version 5.0 */
package n3phele.service.nShell;

public interface ShellTreeConstants
{
  public int JJTSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTFORCOMMAND = 2;
  public int JJTVARIABLE = 3;
  public int JJTBLOCK = 4;
  public int JJTCREATEVM = 5;
  public int JJTOPTION = 6;
  public int JJTLITERALARG = 7;
  public int JJTON = 8;
  public int JJTLOG = 9;
  public int JJTDESTROY = 10;
  public int JJTASSIMILATEVM = 11;
  public int JJTVARIABLEASSIGN = 12;
  public int JJTEXPRESSION = 13;
  public int JJTPASSTHRU = 14;
  public int JJTPIECES = 15;
  public int JJTFILELIST = 16;
  public int JJTFILEELEMENT = 17;


  public String[] jjtNodeName = {
    "script",
    "void",
    "forCommand",
    "variable",
    "block",
    "createvm",
    "option",
    "literalArg",
    "on",
    "log",
    "destroy",
    "assimilateVM",
    "variableAssign",
    "expression",
    "passThru",
    "pieces",
    "fileList",
    "fileElement",
  };
}
/* JavaCC - OriginalChecksum=c335d65c2b7c88ccb4ccb3327501cc3b (do not edit this line) */
