/* Generated By:JavaCC: Do not edit this line. ShellTreeConstants.java Version 5.0 */
package n3phele.service.nShell;

public interface ShellTreeConstants
{
  public int JJTSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTFORCOMMAND = 2;
  public int JJTVARIABLE = 3;
  public int JJTBLOCK = 4;
  public int JJTCREATEVM = 5;
  public int JJTOPTION = 6;
  public int JJTLITERALARG = 7;
  public int JJTON = 8;
  public int JJTLOG = 9;
  public int JJTDESTROY = 10;
  public int JJTVARIABLEASSIGN = 11;
  public int JJTEXPRESSION = 12;
  public int JJTPASSTHRU = 13;
  public int JJTREMOTESHELL = 14;
  public int JJTFILELIST = 15;


  public String[] jjtNodeName = {
    "script",
    "void",
    "forCommand",
    "variable",
    "block",
    "createvm",
    "option",
    "literalArg",
    "on",
    "log",
    "destroy",
    "variableAssign",
    "expression",
    "passThru",
    "remoteShell",
    "fileList",
  };
}
/* JavaCC - OriginalChecksum=287263161a558429e223c4706bd21a2a (do not edit this line) */
