/* Generated By:JJTree&JavaCC: Do not edit this line. ShellConstants.java */
package n3phele.service.nShell;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShellConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int EXPRESSIONWRAPPER = 5;
  /** RegularExpression Id. */
  int ON = 6;
  /** RegularExpression Id. */
  int CREATEVM = 7;
  /** RegularExpression Id. */
  int FORLOOP = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int EXPORT = 11;
  /** RegularExpression Id. */
  int ASSIMILATEVM = 12;
  /** RegularExpression Id. */
  int DESTROY = 13;
  /** RegularExpression Id. */
  int LOG = 14;
  /** RegularExpression Id. */
  int VARIABLEASSIGN = 15;
  /** RegularExpression Id. */
  int VARSTART = 16;
  /** RegularExpression Id. */
  int VARREST = 17;
  /** RegularExpression Id. */
  int WHITESPACE = 18;
  /** RegularExpression Id. */
  int NO_ARG_OPTION = 19;
  /** RegularExpression Id. */
  int OPTION = 20;
  /** RegularExpression Id. */
  int OPTIONSTART = 21;
  /** RegularExpression Id. */
  int OPTIONREST = 22;
  /** RegularExpression Id. */
  int NON_SPACE_ARG = 23;
  /** RegularExpression Id. */
  int ARGSTART = 24;
  /** RegularExpression Id. */
  int ARGREST = 25;
  /** RegularExpression Id. */
  int LITERAL_STRING = 26;
  /** RegularExpression Id. */
  int FILELIST = 27;
  /** RegularExpression Id. */
  int FILESPEC = 28;
  /** RegularExpression Id. */
  int FILESTART = 29;
  /** RegularExpression Id. */
  int FILEREST = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int FILELISTEND = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int LITERALBLOCK = 34;
  /** RegularExpression Id. */
  int VARIABLE = 35;
  /** RegularExpression Id. */
  int EXPRESSION = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int PASSTHRU = 38;
  /** RegularExpression Id. */
  int PASSTHRUSET = 39;
  /** RegularExpression Id. */
  int PASSTHRUMORE = 40;
  /** RegularExpression Id. */
  int WRAPPEDEXPRESSION = 41;

  /** Lexical state. */
  int fileListProcessing = 0;
  /** Lexical state. */
  int DEFAULT = 1;
  /** Lexical state. */
  int argProcessing = 2;
  /** Lexical state. */
  int passThruProcessing = 3;
  /** Lexical state. */
  int wrappedExpressionProcessing = 4;
  /** Lexical state. */
  int expressionProcessing = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "<COMMENT>",
    "<SPACE>",
    "\"$${\"",
    "\"ON\"",
    "\"CREATEVM\"",
    "\"FOR\"",
    "\"IF\"",
    "\"ELSE\"",
    "\"EXPORT\"",
    "\"ASSIMILATEVM\"",
    "\"DESTROY\"",
    "\"LOG\"",
    "<VARIABLEASSIGN>",
    "<VARSTART>",
    "<VARREST>",
    "<WHITESPACE>",
    "<NO_ARG_OPTION>",
    "<OPTION>",
    "<OPTIONSTART>",
    "<OPTIONREST>",
    "<NON_SPACE_ARG>",
    "<ARGSTART>",
    "<ARGREST>",
    "<LITERAL_STRING>",
    "\"[\"",
    "<FILESPEC>",
    "<FILESTART>",
    "<FILEREST>",
    "\",\"",
    "\"]\"",
    "\":\"",
    "<LITERALBLOCK>",
    "<VARIABLE>",
    "<EXPRESSION>",
    "<STRING_LITERAL>",
    "<PASSTHRU>",
    "<PASSTHRUSET>",
    "<PASSTHRUMORE>",
    "<WRAPPEDEXPRESSION>",
  };

}
